[package]
name = "rust-rest-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
mongodb = "2.1.0"
futures = "0.3.25"
serde = "1.0.146"
dotenv = "0.15.0"
thiserror = "1.0.37"
anyhow = "1.0.66"
